services:
  - type: web
    name: Quantum_Core_Server_FULL
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python quantum_core_server_pro.py"
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /total_energy
    numInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1